feat: Add checkbox to enable/disable scroll sync on markdown editor
ExpediaGroup/insights-explorer pull request #512
Opened 2022-02-24 08:35 UTC by LulaV14

This PR adds an experimental feature to be able to scroll the Markdown editor and the Markdown preview containers independently, and adding the functionality to synchronize the scroll position from the editor to the preview based on the position of the Markdown component.

2022-02-24 15:11 UTC, baumandm requested changes

2022-02-24 15:11 UTC, baumandm commented on packages/frontend/src/components/markdown-split-editor/markdown-split-editor.tsx
> +        <Stack direction="row" spacing="1rem" align="stretch">
Swap for an `<HStack>`, it's the same thing but has the row direction baked in.

```suggestion
        <HStack spacing="1rem" align="stretch">
```

2022-02-25 00:54 UTC, baumandm commented on packages/frontend/src/components/markdown-container/chakra-ui-renderer.tsx
> +      console.log(`Image props: ${JSON.stringify(props)}`);
Remove `console.log`

2022-02-25 00:55 UTC, baumandm approved these changes

2022-02-25 00:56 UTC, LulaV14 commented on packages/frontend/src/components/markdown-container/chakra-ui-renderer.tsx
> +      console.log(`Image props: ${JSON.stringify(props)}`);
Oh missed this one 🤦‍♀️

2022-02-25 01:08 UTC, merged